---
framework: mocha
postMerge:
  pattern: 
    - "./test/**/**.js"
preMerge:
  pattern:
    - "./test/**/**.js"
preRun:
     command:
        - npm run build 
postRun:
     command:
        - node --version
version: 1.0
