---
framework: mocha
postMerge:
  pattern: 
    - "./test/**/**.js"
preMerge:
  pattern:
    - "./test/**/**.js"
preRun:
     command:
        - sudo apt-get install firefox-esr
        - npm install
        - npm run build
postRun:
     command:
        - node --version
version: 1.1
